### ISSUE TITLE
Hi i need this code for client

### ISSUE THREAD

**Issue by mafiakb** [lulzyyy/lulzyOgar#4]
How add my client this?

![image](https://cloud.githubusercontent.com/assets/12769609/15939583/f69199ee-2e3d-11e6-8eda-c8dc614cc0c4.png)

**Comment by lulzyyy** [comment]
scaling?

**Comment by mafiakb** [comment]
code javascript for client

**Comment by mafiakb** [comment]
u client is code private? :(
